# Generated by Django 4.1.5 on 2023-04-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='priceb',
            field=models.FloatField(blank=True, default=16),
            preserve_default=False,
        ),
    ]
