# Generated by Django 4.1.5 on 2023-04-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_priceb_product_price_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_b',
            field=models.FloatField(blank=True),
        ),
    ]
