# Generated by Django 4.1.5 on 2023-04-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_image_alter_product_price_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_b',
            field=models.FloatField(),
        ),
    ]
