# Generated by Django 4.1.5 on 2023-05-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_price_b'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_b',
        ),
    ]
