# Generated by Django 4.1.5 on 2023-05-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_product_price_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricex',
            field=models.FloatField(default=16),
            preserve_default=False,
        ),
    ]
