# Generated by Django 4.1.5 on 2023-05-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_newletters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newletters',
            new_name='Newsletter',
        ),
    ]
