# Generated by Django 4.1.5 on 2023-05-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='num',
            field=models.CharField(default=500, max_length=200),
            preserve_default=False,
        ),
    ]
