# Generated by Django 4.1.5 on 2023-05-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_commande_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pop',
            field=models.CharField(default=200, max_length=200),
            preserve_default=False,
        ),
    ]
