# Generated by Django 4.1.5 on 2023-06-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_product_price_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_bar',
            field=models.FloatField(blank=True),
        ),
    ]
