# Generated by Django 4.1.5 on 2023-06-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_product_price_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_bar',
            field=models.FloatField(),
        ),
    ]
