# Generated by Django 4.1.5 on 2023-11-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_product_price_bar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pop',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_bar',
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default=2, upload_to='media'),
            preserve_default=False,
        ),
    ]
