# Generated by Django 4.1.5 on 2023-11-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_remove_product_pop_remove_product_price_bar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='poid',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
