# Generated by Django 4.1.5 on 2023-11-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_product_poid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='couleur',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='matiere',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='taille',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
