# Generated by Django 4.1.5 on 2023-11-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_product_couleur_product_matiere_product_taille'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='poid',
            new_name='poids',
        ),
        migrations.AddField(
            model_name='product',
            name='dimension',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
